language: android
android:
  components:
      - platform-tools
      - tools
      - build-tools-25.0.3
      - android-25
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      - addon-google_apis-google-25
      - sys-img-armeabi-v7a-android-25
      - sys-img-x86-android-15
  licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+
jdk:
  - oraclejdk8
before_install:
 - rvm install 2.0.0
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
 directories:
 - ~/.android
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
script:
 - ./scripts/travis.sh
after_script:
 - mkdir -p $TRAVIS_BUILD_DIR/junit/
 - find . -type d -regex ".*/reports/tests$" -exec cp -r {} $TRAVIS_BUILD_DIR/junit/ \;

